import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ToastProvider from "@/providers/ToastProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <title>Sabores Brasileiros</title>
      <meta httpEquiv="Content-Type" content="text/html; charset=utf-8" />
      <meta
        name="description"
        content="Sabores Brasileiros: Onde Cada Prato Conta uma História de Sabor e Tradição!"
      />
      <meta
        name="keywords"
        content="restaurante, sabores brasileiros, tradicao, sabor e historia"
      />
      <meta name="author" content="Arlisson Costa" />
      <body className="mx-auto max-w-7xl px-2">
        <Navbar />
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
